In [1]:
import os
import cv2
import numpy as np
import pandas as pd

In [2]:

# Define the image size
IMG_SIZE = 224

In [3]:

# Define the class labels
class_labels = ['ADI', 'BACK', 'DEB', 'LYM', 'MUC', 'MUS', 'NORM', 'STR', 'TUM']

In [4]:
# Load the images and store the pixel values in a numpy array
data = []
labels = []
for class_label in class_labels:
    path = os.path.join('C:/Users/Sc/Desktop/Colorectal Cancer/Dataset/CRC-VAL-HE-7K', class_label)
    for img_file in os.listdir(path):
        img_path = os.path.join(path, img_file)
        img = cv2.imread(img_path)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img.astype('float32') / 255.0  # normalize pixel values between 0 and 1
        data.append(img.flatten())
        labels.append(class_label)

data = np.array(data)
labels = np.array(labels)

In [5]:
# Combine the data and labels into a pandas dataframe
df = pd.DataFrame(data)
df['label'] = labels

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,150519,150520,150521,150522,150523,150524,150525,150526,150527,label
0,0.866667,0.796078,0.894118,0.901961,0.768627,0.878431,0.913725,0.811765,0.901961,0.870588,...,0.788235,0.666667,0.772549,0.819608,0.717647,0.803922,0.850980,0.776471,0.831373,ADI
1,0.874510,0.788235,0.835294,0.870588,0.784314,0.819608,0.878431,0.796078,0.843137,0.890196,...,0.678431,0.521569,0.741176,0.701961,0.545098,0.760784,0.721569,0.572549,0.792157,ADI
2,0.933333,0.894118,0.929412,0.952941,0.929412,0.945098,0.941176,0.909804,0.941176,0.870588,...,0.694118,0.482353,0.760784,0.650980,0.439216,0.713726,0.584314,0.376471,0.635294,ADI
3,0.952941,0.925490,0.952941,0.956863,0.929412,0.952941,0.956863,0.929412,0.952941,0.952941,...,0.964706,0.952941,0.960784,0.937255,0.925490,0.941176,0.898039,0.850980,0.886275,ADI
4,0.803922,0.580392,0.780392,0.760784,0.592157,0.792157,0.752941,0.607843,0.800000,0.803922,...,0.698039,0.443137,0.670588,0.878431,0.776471,0.952941,0.854902,0.670588,0.945098,ADI

In [6]:
# Save the dataframe as a CSV file
df.to_csv('images_CRC_7K.csv', index=False)

KeyboardInterrupt: